### ISSUE TITLE
Poprawa inputu expense w expenses popup

### ISSUE THREAD

**Issue by oopjot** [oevadee/zip-app#29]
Nie można dodawać expenses zmiennoprzecinkowych, jest int a powinien być float.
Na mobile nie można wpisać liczby ujemnej, trzeba najpierw selectem dać -1 a potem dopiero zacząć pisać

**Comment by oevadee** [comment]
@oopjot mogę dodawać zarówno liczby zmiennoprzecinkowe oraz liczby ujemne. Czy problem nadal u Ciebie występuje? Jak nie to zamknij issue

**Comment by oevadee** [comment]
Dobra gotowe, zamykam
