### ISSUE TITLE
Zdeployować bazę danych.

### ISSUE THREAD

**Issue by oevadee** [oevadee/zip-app#4]
Trzeba zdeployować bazę. Problem w tym, że większość operatorów ma to w opór drogo.

**Pjotr** rozeznaj się jak możemy to zrobić kosztem nie przekraczającym 30/40 zeta miesięcznie

> https://www.reddit.com/r/Database/comments/k0fab2/cheapest_way_to_host_a_neo4j_graph_database_for/gdhx7im/

**Comment by oevadee** [comment]
Dobra jednak aura odpada bo jest za droga. Da się zdeployować front/back/db na heroku więc chyba tak też zrobimy. Stworzę na to osobne issue

**Comment by oopjot** [comment]
hehehe
