### ISSUE TITLE
Dodać możliwość dodawania własnych zdjęć.

### ISSUE THREAD

**Issue by oevadee** [oevadee/zip-app#46]
Na chwilę obecną bierzemy zdjęcia z url'i z fb i inny sociali. Problem jest wtedy kiedy ktoś nie ma dodanej innej osoby jako znajomego i wyświetla mu się sam avatar. Trzeba dodać możliwość wrzucania własnych zdjęć na server

**Comment by oopjot** [comment]
Jeszcze pare rzeczy

**Comment by oevadee** [comment]
Naprawiłem problem z uploadem plików. Zamykam issue
