### ISSUE TITLE
Zdeployować front + back + db

### ISSUE THREAD

**Issue by oevadee** [oevadee/zip-app#5]
Trzeba zdeployować front i back

Trzeba zdeployować bazę. Problem w tym, że większość operatorów ma to w opór drogo.

Pjotr rozeznaj się jak możemy to zrobić kosztem nie przekraczającym 30/40 zeta miesięcznie

https://www.reddit.com/r/Database/comments/k0fab2/cheapest_way_to_host_a_neo4j_graph_database_for/gdhx7im/

**Comment by oopjot** [comment]
zajme sie tym *____* :\:

**Comment by oevadee** [comment]
Aplikacja zdeployowana, zamykam issue
